NAME = libft.a
CC = gcc
CFLAGS = -Wall -Wextra -Werror
SRCS 	= ft_atoi.c\
		        ft_bzero.c\
				ft_calloc.c\
				ft_isalnum.c\
				ft_isalpha.c\
				ft_isascii.c\
				ft_isdigit.c\
				ft_toupper.c\
				ft_islower.c\
				ft_isprint.c\
				ft_memchr.c\
				ft_memcmp.c\
				ft_memcpy.c\
				ft_memmove.c\
				ft_memset.c\
				ft_strchr.c\
				ft_strdup.c\
				ft_strncmp.c\
				ft_strnstr.c\
				ft_strrchr.c\
				ft_strlen.c\
				ft_strlcpy.c\
				ft_strlcat.c\
				ft_substr.c\
				ft_strjoin.c\
				ft_strtrim.c\
				ft_itoa.c\
				ft_strmapi.c\
				ft_striteri.c\
				ft_putchar_fd.c\
				ft_putstr_fd.c\
				ft_putendl_fd.c\
				ft_putnbr_fd.c
					
OBJS 	= ${SRCS:.c=.o} 
HEADER 	= includes
LIBR 	= ranlib
LIBC 	= ar -rc
RM 		= rm -f

.c.o:
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o} -I${HEADER}

${NAME}: ${OBJS}
		 ${LIBC} ${NAME} ${OBJS}
		 ${LIBR} ${NAME}

bonus: ${OBJS}

all:${NAME}

clean :
		${RM} ${OBJS}

fclean :clean
		${RM} ${NAME}

re:fclean all

.PHONY: all clean fclean re
